### ISSUE TITLE
Ta bort if-satserna

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#11]
Ta bort if-satserna i SQLBasedProductLine där products==null: för att den alltid ska läsa databasen, varje gång. Står på 2 ställen, rad 24 och 31.

**Comment by johanbrandr** [comment]
Fixat koden lägger över i test

**Comment by hectorlyngfelt** [comment]
Koden är testad. Returnerar produkter med korrekt JSON

**Comment by johanbrandr** [comment]
Good job Mr Lyngfelt!

**Comment by hectorlyngfelt** [comment]
Allt fungerar som det ska. Klarskriver ticket.
