### ISSUE TITLE
Utöka tabellen product

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#12]
Lägg till kolumnen insertDate.

**Comment by EllinorStomdal** [comment]
Jag har lagt till kolumnen insertDate i tabellen product. Inväntar övriga uppdateringar i databasen innan jag skickar vidare till testning.

**Comment by Emelie0213** [comment]
Har tagit över för test, gjordes under grupprogrammeringen.

**Comment by Emelie0213** [comment]
Det gick att lägga in en testprodukt, tabellen fungerar.
