### ISSUE TITLE
Skapa tabellen för förändringar i pris

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#13]
Lägg till en separat tabell för förändringar med kolumnerna nr (Foreign key till "nr" i product), cangeDate och price.

**Comment by axelfilipsson** [comment]
la till en separat tabell med namnet priceChange

**Comment by axelfilipsson** [comment]
Jag la till en tabell "priceChanges"  I databases

**Comment by axelfilipsson** [comment]
Råkade stänga ticketen, öppnar igen och la till i test.

**Comment by Emelie0213** [comment]
Har testat att lägga in testprodukter, det funkar med constraits.
