### ISSUE TITLE
Hämta XML fil

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#14]
Det finns ett skript som skapar mappen resources med filen sortiment.xml, glöm ej att ändra premission (chmd +X skriptnamn.sh)
https://raw.githubusercontent.com/progund/tig015-weekly/master/weekly02/get_latest_file.sh

**Comment by johanbrandr** [comment]
Script is made and pushed to dev branch

**Comment by Emelie0213** [comment]
Vi har ändrat skriptet så att det går att köra från sbserver och filen sortiment.xml hamnar i resourses-mappen.

**Comment by hectorlyngfelt** [comment]
Testat skriptet, det hämtar den senaste xml-filen och skriver över den gamla. Alla funktioner fungerar som de ska. Avslutar ticket.
