### ISSUE TITLE
För in de parsade produkterna (från XML) i databasen.

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#15]
Vi parsar XML i XMLBasedProductLine.java
och för in dem mha SQLInserExporter.java - Behöver kodas om

**Comment by Emelie0213** [comment]
Vi har diskuterat problemet i grupp och överlåter till Ellinor och Hector att fortsätta och slutföra issuen

**Comment by hectorlyngfelt** [comment]
SQLbasedProductLine hämtar nu nuvarande xml-fil och parsar den till databasen

**Comment by Emelie0213** [comment]
Har granskat koden
