### ISSUE TITLE
Gör en ny javaklass CompareChanges.java

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#17]
Som ska innehålla en metod för att jämför nya XML-filer med referensen.

**Comment by johanbrandr** [comment]
Skapat CompareChanges-klassen

**Comment by axelfilipsson** [comment]
Skapade metoden getXMLProductLine

**Comment by johanbrandr** [comment]
> Skapade metoden getXMLProductLine

Hejaheja!!

**Comment by johanbrandr** [comment]
Ändrade i toSQLCompareDateString så metoden alltid visar produkter som är 4 månader "nya"

**Comment by johanbrandr** [comment]
Flyttade toSQLCompareDateString till SQLInsertExporter

**Comment by johanbrandr** [comment]
Skapade metoden sqlStatement för att skapa connection med databasen samt printa ut rs
