### ISSUE TITLE
Gör ett skript för att läsa in nya XML-filer

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#19]
Ska ta den nya XML-filen som argument

**Comment by hectorlyngfelt** [comment]
Ändrat i skriptet så den inte bara hämtar hem den nya xml filen, utan även läser in i databasen. För tillfället läses dock "referens-databasen" in. Framtida funktion kommer vara att läsa in enbart nya produkter. Lägger över i test

**Comment by hectorlyngfelt** [comment]
Skriptet läser nu in nya produkter från senaste XML och stoppar in dessa i databasen

**Comment by hectorlyngfelt** [comment]
Scriptet sorterar nu ut skillnaden i pris mellan produkter i databasen och senaste XML

**Comment by hectorlyngfelt** [comment]
Lägger över till Testing

**Comment by Emelie0213** [comment]
Har granskat koden och sett att det fungerar
