### ISSUE TITLE
Gör en textbaserad meny: Sortiment, Nyheter, Historik

### ISSUE THREAD

**Issue by axelfilipsson** [axelfilipsson/TIG059#20]
Så att kunden kan läsa av förändringarna och så att vi kan se att alt fungerar

**Comment by Emelie0213** [comment]
Vi har löst den första funktionen som visar alla aktuella produkter

**Comment by Emelie0213** [comment]
Vi inväntar kod för att kunna fortsätta med nästa funktion: att visa nyheter

**Comment by Emelie0213** [comment]
Ändrade beskrivningen/namnet så att det stämmer överens med de funktioner som ska ingå i den textbaserade menyn.

**Comment by Emelie0213** [comment]
Jag och Ellinor arbetar med den tredje funktionen, att komma åt prisförändringar över tid.

**Comment by EllinorStomdal** [comment]
Emelie och jag skapade en ny branch "PriceSearch" för att arbeta med historiken.

**Comment by johanbrandr** [comment]
Nyheter och Sortiment är klart

**Comment by EllinorStomdal** [comment]
Emelie och jag har ändrat gjort klassen PriceSearch som gör det möjligt att via den textbaserade menyn söka efter prisutveckling för en specifik produkt från databasen.
